# Generated by Django 5.2.4 on 2025-07-19 14:27

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.png', null=True, upload_to=core.user.models.user_avatar_path),
        ),
    ]
