version: "3.8"

services:
  web:
    container_name: postgram-api
    image: postman-api-drf:latest
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env  
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
  
  db:
    container_name: postgram-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: postgram-nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  

    