name: FullStack CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend-test:
    name: Test Backend 
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend 
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    env:
          USE_S3: FALSE
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_S3_BUCKET_NAME: dummy
          AWS_REGION: dummy
          SUPERUSER_USERNAME: dummy
          SUPERUSER_EMAIL: dummy
          SUPERUSER_PASSWORD: dummy
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_HOST: localhost
          DB_PORT: 5432
          ALLOWED_HOSTS: localhost
          DJANGO_SECRET_KEY: dummysecret
          CORS_ALLOWED_ORIGINS: http://localhost:3000
          OPENAI_API_KEY: dummy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run migrations
        run: |
          python manage.py migrate
      
      - name: Run Pytest
        
        run: |
          pytest 

